### PR TITLE
Fixing zoom & undo reset

### LINKED ISSUE #245: grey out undo reset when sliders are locked
Quote from issue #234 :
New site behaviors

There's been some new site behaviors added in that I wanted to note, just in case they were undesired.
1. When the user locks the sliders, the reset button also becomes greyed out. Before it was completely usable, but now the user cannot reset the sliders if they are locked. 

> We agree that this is a desired behavior.

However, I retained the ability for the user to undo a reset while the sliders are locked. Should the undo reset button be greyed out as well? It wouldn't be hard to implement.

> We think that the reset button should be greyed out since we are saying "locked" is "locked".
1. I greyed out the "undo reset" settings option when the undo reset button is disabled. I figured that it wasn't greyed out originally due to a bug, but I figured I'd note it anyways.

> Do you mean in the format menu?  We are confused.

### PR DESCRIPTION
**Pull request by mihirsamdarshi**
This PR fixes #245 & #561
Edit:
Added #708 to the list
Added #437 to the list
Added #753 to the list

### CODE REVIEW

**Comment by mihirsamdarshi** [comment]
@dondi ready for review

**Comment by mihirsamdarshi** [comment]
Pull Request Checklist
- [ ] Travis C.I. build passes
- [ ] All four Demos look as expected when loaded
- [ ] Reload works as expected
- [ ] Loading file with Error brings up error modal, and it looks as expected
- [ ] Loading file with Warning brings up warnings modal
- [ ] Import works for both SIF and GraphML
- [ ] Graph can be exported to SIF and GraphML
- [ ] Print works as expected
- [ ] Restrict graph to viewport works as expected (check/uncheck)
- [ ] Viewport Size Changing works as expected (small/medium/large/fit)
- [ ] Toggle between Grid Layout and Force Graph Layout works as expected
- [ ] Force Graph Parameter Sliders change the number above them and have an effect on the graph
- [ ] Locking/Unlocking/Resetting/Undo Resetting the force graph parameters works as expected
- [ ] Enabling and disabling node coloring works as expected
- [ ] Node coloring options work as expected (selection top/bottom dataset, averaging values, changing max value)
- [ ] Weighted graph loaded with the "default to black edges" option checked appears as expected
- [ ] Hide/Show Weights works as expected (always/never/upon mouseover)
- [ ] Edge Weight Normalization Factor can be changed (set/reset)
- [ ] Gray Edge Threshold can be changed, slider changes the number and has an effect on the graph
- [ ] Checking Show Gray Edges as Dashed works as expected (check/uncheck)
- [ ] D-pad left/right/top/bottom/center works as expected
- [ ] Zoom slider changes number and has effect on graph (viewport and menu)
- [ ] Right click on a node opens gene page, page is populated with correct data

**Comment by mihirsamdarshi** [comment]
Because all comments have been resolved, and all testing has been done, as soon as Travis CI passes, I will merge this PR and refresh beta

File: web-client/public/js/grnstate.js [hunk 1]
```diff
@@ -71,6 +71,10 @@ export const grnState = {
     dashedLine: false,
 
     annotateLinks: () => annotateLinks(currentNetwork),
+
+// Zoom Parameter
+    zoomValue: 4,
```
Comment (dondi) [inline web-client/public/js/grnstate.js]: @mihirsamdarshi Actually the protocol is you _do_ wait for an approving review before merging a PR even after you have responded to feedback. Because, for example, you might miss something like this. The earlier `4` was replaced with `DEFAULT_ZOOM_VALUE`, but what about this one?

The code reviewer is supposed to explicitly re-approve a PR before it gets merged, precisely because there might be loose ends like the one above.
